contact_links:
  - name: Googleフォーム
    url: https://docs.google.com/forms/d/e/1FAIpQLSf0N-X_u_abi8rrWHVDdiK3YeYuQ7J1f8bQAy6QTD-OR94DWQ/viewform?usp=sf_link
    about: 入力しやすいフォーム形式でフィードバックを送る。アカウントが無くても、送信できます。
